name: update changelog

on:
  workflow_call:
    inputs:
      branch:
        description: 'Target branch'
        type: string
        default: ${{ github.event.release.target_commitish }}
      version:
        description: 'Released version'
        type: string
        default: ${{ github.event.release.tag_name }}
      notes:
        description: 'Release notes'
        type: string
        default: ${{ github.event.release.body }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Check if branch and release match
        if: ${{ inputs.branch != 'main' && inputs.branch != 'master' }}
        id: guard
        run: |
          NUMERIC_VERSION="${RELEASE_TAG_NAME#v}"
          MAJOR_VERSION="${NUMERIC_VERSION%%.*}"
          BRANCH_MAJOR_VERSION="${BRANCH%%.*}"

          echo "MAJOR_VERSION=$(echo $MAJOR_VERSION)" >> $GITHUB_OUTPUT;
          echo "BRANCH_MAJOR_VERSION=$(echo $BRANCH_MAJOR_VERSION)" >> $GITHUB_OUTPUT;

          if [ "$MAJOR_VERSION" != "$BRANCH_MAJOR_VERSION" ]; then
            echo "Mismatched versions! Aborting."
            VERSION_MISMATCH='true';
          else
            echo "Versions match! Proceeding."
            VERSION_MISMATCH='false';
          fi
          echo "VERSION_MISMATCH=$(echo $VERSION_MISMATCH)" >> $GITHUB_OUTPUT;
        env:
          BRANCH: ${{ inputs.branch }}
          RELEASE_TAG_NAME: ${{ inputs.version }}

      - name: Fail if branch and release tag do not match
        if: ${{ steps.guard.outputs.VERSION_MISMATCH == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Release version does not match branch major version. Aborting.')

      - name: Extract release date from git tag
        id: release_date
        run: |
          TIMESTAMP=$(git log -1 --date=unix --format=%ad '${{ inputs.version }}')
          FORMATTED_DATE=$(date -u -d @$TIMESTAMP +%Y-%m-%d)
          echo "date=$FORMATTED_DATE" >> $GITHUB_OUTPUT

      - name: Debug notes input
        run: |
          echo ">>> Notes <<<"
          echo "${{ inputs.notes }}"
          echo ">>> End <<<"

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ inputs.notes }}
          latest-version: ${{ inputs.version }}
          compare-url-target-revision: ${{ inputs.branch }}
          parse-github-usernames: true
          path-to-changelog: CHANGELOG.md

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ inputs.branch }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
